---
# {{ ansible_managed }}
# https://github.com/prometheus/blackbox_exporter

modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
  rsync_banner:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^@RSYNCD:"
  tcp_connect:
    prober: tcp
    timeout: 5s
  ssh_banner:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^SSH-2.0-"
  icmp:
    prober: icmp
    timeout: 5s
